[package]
name = "bslite-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs_core = { path = "../bs_core", version = "0.1.0" }
anyhow.workspace = true
tokio.workspace = true